name: Draft new release
on:
  push:
    tags:
     - 'v1.[0-9]+'

permissions:
  contents: write
  packages: write

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Setup
      env:
        SWIG_VERSION: 4.3.1
      run: |
        sudo apt update
        sudo apt install -y libpcre2-dev libboost-dev tofrodos
        wget http://downloads.sourceforge.net/project/swig/swig/swig-${SWIG_VERSION}/swig-${SWIG_VERSION}.tar.gz \
            && tar xfz swig-${SWIG_VERSION}.tar.gz \
            && rm swig-${SWIG_VERSION}.tar.gz \
            && cd swig-${SWIG_VERSION} \
            && ./configure --prefix=/usr CXXFLAGS=-O3 \
            && make -j 4 && sudo make install \
            && cd .. && rm -rf swig-${SWIG_VERSION}
    - name: Configure
      run: |
        ./autogen.sh
        ./configure
    - name: Make tarballs
      run: |
        mkdir tarballs
        make dist
        mv QuantLib-*.tar.gz tarballs
        cd tarballs && ../tools/tgz2zip *.tar.gz && ls -lh
    - name: Extract version
      run: |
        echo ${{ github.ref_name }} | awk -F '[v-]' '{ print "VERSION_NUMBER=" $2 }' | tee -a $GITHUB_ENV
    - name: Prepare release notes
      run: |
        echo "Downloads:" >> tarballs/notes.txt
        echo "==========" >> tarballs/notes.txt
        echo "" >> tarballs/notes.txt
        echo "- [QuantLib-SWIG-${VERSION_NUMBER}.tar.gz](https://github.com/lballabio/QuantLib-SWIG/releases/download/v${VERSION_NUMBER}/QuantLib-SWIG-${VERSION_NUMBER}.tar.gz)" >> tarballs/notes.txt
        echo "- [QuantLib-SWIG-${VERSION_NUMBER}.zip](https://github.com/lballabio/QuantLib-SWIG/releases/download/v${VERSION_NUMBER}/QuantLib-SWIG-${VERSION_NUMBER}.zip)" >> tarballs/notes.txt
        echo "" >> tarballs/notes.txt
        awk '/Full list of pull requests/{ exit } { print }' News.md >> tarballs/notes.txt
    - name: Create draft release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ github.ref_name }} \
            --title "${VERSION_NUMBER}" \
            --draft \
            --notes-file tarballs/notes.txt \
            --generate-notes \
            tarballs/*.tar.gz tarballs/*.zip
